In [1]:
from sqlalchemy import create_engine, text

In [2]:
database_name = 'prescribers'    # Fill this in with your prescribers database name

connection_string = f"postgresql://postgres:postgres@localhost:5432/{database_name}"

In [3]:
engine = create_engine(connection_string)

In [4]:
import pandas as pd

In [28]:
prescrib = '''
SELECT * FROM prescriber;
'''
with engine.connect() as connection:
   prescriber = pd.read_sql(text(prescrib), con = connection)

prescriber.head()

,npi,nppes_provider_last_org_name,nppes_provider_first_name,nppes_provider_mi,nppes_credentials,nppes_provider_gender,nppes_entity_code,nppes_provider_street1,nppes_provider_street2,nppes_provider_city,nppes_provider_zip5,nppes_provider_zip4,nppes_provider_state,nppes_provider_country,specialty_description,description_flag,medicare_prvdr_enroll_status
0,1.003000e+09,BLAKEMORE,ROSIE,K,FNP,F,I,TENNESSEE PRISON FOR WOMEN,3881 STEWARTS LANE,NASHVILLE,37243,0001,TN,US,Nurse Practitioner,S,N
1,1.003012e+09,CUDZILO,COREY,None,M.D.,M,I,2240 SUTHERLAND AVE,SUITE 103,KNOXVILLE,37919,2333,TN,US,Pulmonary Disease,S,E
2,1.003013e+09,GRABENSTEIN,WILLIAM,P,M.D.,M,I,1822 MEMORIAL DR,None,CLARKSVILLE,37043,4605,TN,US,Family Practice,S,E
3,1.003014e+09,OTTO,ROBERT,J,M.D.,M,I,2400 PATTERSON STREET SUITE 100,None,NASHVILLE,37203,2786,TN,US,Orthopedic Surgery,S,E
4,1.003018e+09,TODD,JOSHUA,W,M.D.,M,I,1819 W CLINCH AVE,SUITE 108,KNOXVILLE,37916,2435,TN,US,Cardiology,S,E

In [30]:
cbsa1 = '''
SELECT * FROM prescriber;
'''
with engine.connect() as connection:
    cbsa = pd.read_sql(text(cbsa1), con = connection)

cbsa.head()

,npi,nppes_provider_last_org_name,nppes_provider_first_name,nppes_provider_mi,nppes_credentials,nppes_provider_gender,nppes_entity_code,nppes_provider_street1,nppes_provider_street2,nppes_provider_city,nppes_provider_zip5,nppes_provider_zip4,nppes_provider_state,nppes_provider_country,specialty_description,description_flag,medicare_prvdr_enroll_status
0,1.003000e+09,BLAKEMORE,ROSIE,K,FNP,F,I,TENNESSEE PRISON FOR WOMEN,3881 STEWARTS LANE,NASHVILLE,37243,0001,TN,US,Nurse Practitioner,S,N
1,1.003012e+09,CUDZILO,COREY,None,M.D.,M,I,2240 SUTHERLAND AVE,SUITE 103,KNOXVILLE,37919,2333,TN,US,Pulmonary Disease,S,E
2,1.003013e+09,GRABENSTEIN,WILLIAM,P,M.D.,M,I,1822 MEMORIAL DR,None,CLARKSVILLE,37043,4605,TN,US,Family Practice,S,E
3,1.003014e+09,OTTO,ROBERT,J,M.D.,M,I,2400 PATTERSON STREET SUITE 100,None,NASHVILLE,37203,2786,TN,US,Orthopedic Surgery,S,E
4,1.003018e+09,TODD,JOSHUA,W,M.D.,M,I,1819 W CLINCH AVE,SUITE 108,KNOXVILLE,37916,2435,TN,US,Cardiology,S,E

In [32]:
drug1 = '''
SELECT * FROM prescriber;
'''
with engine.connect() as connection:
    drug = pd.read_sql(text(drug1), con = connection)

drug.head()

,npi,nppes_provider_last_org_name,nppes_provider_first_name,nppes_provider_mi,nppes_credentials,nppes_provider_gender,nppes_entity_code,nppes_provider_street1,nppes_provider_street2,nppes_provider_city,nppes_provider_zip5,nppes_provider_zip4,nppes_provider_state,nppes_provider_country,specialty_description,description_flag,medicare_prvdr_enroll_status
0,1.003000e+09,BLAKEMORE,ROSIE,K,FNP,F,I,TENNESSEE PRISON FOR WOMEN,3881 STEWARTS LANE,NASHVILLE,37243,0001,TN,US,Nurse Practitioner,S,N
1,1.003012e+09,CUDZILO,COREY,None,M.D.,M,I,2240 SUTHERLAND AVE,SUITE 103,KNOXVILLE,37919,2333,TN,US,Pulmonary Disease,S,E
2,1.003013e+09,GRABENSTEIN,WILLIAM,P,M.D.,M,I,1822 MEMORIAL DR,None,CLARKSVILLE,37043,4605,TN,US,Family Practice,S,E
3,1.003014e+09,OTTO,ROBERT,J,M.D.,M,I,2400 PATTERSON STREET SUITE 100,None,NASHVILLE,37203,2786,TN,US,Orthopedic Surgery,S,E
4,1.003018e+09,TODD,JOSHUA,W,M.D.,M,I,1819 W CLINCH AVE,SUITE 108,KNOXVILLE,37916,2435,TN,US,Cardiology,S,E

In [34]:
fips_county1 = '''
SELECT * FROM prescriber;
'''
with engine.connect() as connection:
    fips_county = pd.read_sql(text(fips_county1), con = connection)

fips_county.head()

,npi,nppes_provider_last_org_name,nppes_provider_first_name,nppes_provider_mi,nppes_credentials,nppes_provider_gender,nppes_entity_code,nppes_provider_street1,nppes_provider_street2,nppes_provider_city,nppes_provider_zip5,nppes_provider_zip4,nppes_provider_state,nppes_provider_country,specialty_description,description_flag,medicare_prvdr_enroll_status
0,1.003000e+09,BLAKEMORE,ROSIE,K,FNP,F,I,TENNESSEE PRISON FOR WOMEN,3881 STEWARTS LANE,NASHVILLE,37243,0001,TN,US,Nurse Practitioner,S,N
1,1.003012e+09,CUDZILO,COREY,None,M.D.,M,I,2240 SUTHERLAND AVE,SUITE 103,KNOXVILLE,37919,2333,TN,US,Pulmonary Disease,S,E
2,1.003013e+09,GRABENSTEIN,WILLIAM,P,M.D.,M,I,1822 MEMORIAL DR,None,CLARKSVILLE,37043,4605,TN,US,Family Practice,S,E
3,1.003014e+09,OTTO,ROBERT,J,M.D.,M,I,2400 PATTERSON STREET SUITE 100,None,NASHVILLE,37203,2786,TN,US,Orthopedic Surgery,S,E
4,1.003018e+09,TODD,JOSHUA,W,M.D.,M,I,1819 W CLINCH AVE,SUITE 108,KNOXVILLE,37916,2435,TN,US,Cardiology,S,E

In [ ]:
ovrdose_dths = '''
SELECT * FROM prescriber;
'''
with engine.connect() as connection:
    overdose_deaths = pd.read_sql(text(ovrdose_dths), con = connection)

overdose_deaths.head()

In [36]:
pop = '''
SELECT * FROM prescriber;
'''

with engine.connect() as connection:
    population = pd.read_sql(text(pop), con = connection)

population.head()

,npi,nppes_provider_last_org_name,nppes_provider_first_name,nppes_provider_mi,nppes_credentials,nppes_provider_gender,nppes_entity_code,nppes_provider_street1,nppes_provider_street2,nppes_provider_city,nppes_provider_zip5,nppes_provider_zip4,nppes_provider_state,nppes_provider_country,specialty_description,description_flag,medicare_prvdr_enroll_status
0,1.003000e+09,BLAKEMORE,ROSIE,K,FNP,F,I,TENNESSEE PRISON FOR WOMEN,3881 STEWARTS LANE,NASHVILLE,37243,0001,TN,US,Nurse Practitioner,S,N
1,1.003012e+09,CUDZILO,COREY,None,M.D.,M,I,2240 SUTHERLAND AVE,SUITE 103,KNOXVILLE,37919,2333,TN,US,Pulmonary Disease,S,E
2,1.003013e+09,GRABENSTEIN,WILLIAM,P,M.D.,M,I,1822 MEMORIAL DR,None,CLARKSVILLE,37043,4605,TN,US,Family Practice,S,E
3,1.003014e+09,OTTO,ROBERT,J,M.D.,M,I,2400 PATTERSON STREET SUITE 100,None,NASHVILLE,37203,2786,TN,US,Orthopedic Surgery,S,E
4,1.003018e+09,TODD,JOSHUA,W,M.D.,M,I,1819 W CLINCH AVE,SUITE 108,KNOXVILLE,37916,2435,TN,US,Cardiology,S,E

In [ ]:
prescrip = '''
SELECT * FROM prescriber;
'''
with engine.connect() as connection:
    prescription = pd.read_sql(text(prescrip), con = connection)

prescription.head()

In [38]:
zip = '''
SELECT * FROM prescriber;
'''
with engine.connect() as connection:
    zip_fips = pd.read_sql(text(zip), con = connection)

zip_fips.head()

,npi,nppes_provider_last_org_name,nppes_provider_first_name,nppes_provider_mi,nppes_credentials,nppes_provider_gender,nppes_entity_code,nppes_provider_street1,nppes_provider_street2,nppes_provider_city,nppes_provider_zip5,nppes_provider_zip4,nppes_provider_state,nppes_provider_country,specialty_description,description_flag,medicare_prvdr_enroll_status
0,1.003000e+09,BLAKEMORE,ROSIE,K,FNP,F,I,TENNESSEE PRISON FOR WOMEN,3881 STEWARTS LANE,NASHVILLE,37243,0001,TN,US,Nurse Practitioner,S,N
1,1.003012e+09,CUDZILO,COREY,None,M.D.,M,I,2240 SUTHERLAND AVE,SUITE 103,KNOXVILLE,37919,2333,TN,US,Pulmonary Disease,S,E
2,1.003013e+09,GRABENSTEIN,WILLIAM,P,M.D.,M,I,1822 MEMORIAL DR,None,CLARKSVILLE,37043,4605,TN,US,Family Practice,S,E
3,1.003014e+09,OTTO,ROBERT,J,M.D.,M,I,2400 PATTERSON STREET SUITE 100,None,NASHVILLE,37203,2786,TN,US,Orthopedic Surgery,S,E
4,1.003018e+09,TODD,JOSHUA,W,M.D.,M,I,1819 W CLINCH AVE,SUITE 108,KNOXVILLE,37916,2435,TN,US,Cardiology,S,E

In [ ]:
# Which Tennessee counties had a disproportionately high number of opioid prescriptions?

In [ ]:
# Who are the top opioid prescibers for the state of Tennessee?

In [ ]:
# What did the trend in overdose deaths due to opioids look like in Tennessee from 2015 to 2018?

In [ ]:
# Is there an association between rates of opioid prescriptions and overdose deaths by county?

In [ ]:
# Is there any association between a particular type of opioid and number of overdose deaths?